### ISSUE TITLE
demo url or screenshots

### ISSUE THREAD

**Issue by johnfelipe** [tropo/voicebase-php#1]

**Comment by akalsey** [comment]
It's an application that runs on a phone call. There is no visual UI.

**Comment by johnfelipe** [comment]
How can i hosting player in my own server:

https://app.voicebase.com/demoPage/55c947fc78e07 
https://app.voicebase.com/demoPage/55c95c19a8bc7 
https://app.voicebase.com/demoPage/55c964c996624

**Comment by akalsey** [comment]
For questions about VoiceBase, please direct them to VoiceBase. This repo is a demo from Tropo, a telephone communications API, showing how to use Voicebase to transcribe Tropo telephone calls.
